name: Delete fullstack.mp4

on:
  workflow_dispatch:

jobs:
  delete_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Delete file
        run: |
          git rm fullstack.mp4
          git config user.name "Your Name"
          git config user.email "you@example.com"
          git commit -m "Delete fullstack.mp4"
          git push
